# Generated by Django 2.1 on 2018-08-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fas_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fasuser',
            options={'ordering': ('created',)},
        ),
    ]
