# Generated by Django 2.1 on 2018-08-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fas_backend', '0002_auto_20180827_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fasuser',
            options={'default_permissions': (), 'ordering': ('created',)},
        ),
    ]
